if(NOT THREADS_NUM)
	set(THREADS_NUM 1)
endif()

set(GFLAGS_NAME gflags-2.2.2)
set(GFLAGS_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${GFLAGS_NAME})
set(GFLAGS_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${GFLAGS_NAME})
set(GFLAGS_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${GFLAGS_NAME}-build)
set(GFLAGS_HEADERS ${GFLAGS_DEST}/include)
set(GFLAGS_LIBRARIES ${GFLAGS_DEST}/lib)
set(GFLAGS_CONFIG " \
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
")
set(OPENCV_BUILDCMD " \
    ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")

local_repo_cmake(
    ${GFLAGS_NAME}
    SOURCE ${GFLAGS_SOURCE}
    BUILD ${GFLAGS_BUILD}
    RELEASE
    OPTIONS ${GFLAGS_CONFIG}
    DESTINATION ${GFLAGS_DEST}
    BUILD_COMMAND ${GFLAGS_BUILDCMD}
)

include_directories(${GFLAGS_HEADERS})
link_directories(${GFLAGS_LIBRARIES})
