if(NOT THREADS_NUM)
	set(THREADS_NUM 1)
endif()

set(GTEST_NAME gtest-1.12.0)
set(GTEST_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${GTEST_NAME})
set(GTEST_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${GTEST_NAME})
set(GTEST_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${GTEST_NAME}-build)
set(GTEST_HEADERS ${GTEST_DEST}/include)
set(GTEST_LIBRARIES ${GTEST_DEST}/lib)
set(GTEST_CONFIG " \
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
")
set(GTEST_BUILDCMD " \
    ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")

local_repo_cmake(
    ${GTEST_NAME}
    SOURCE ${GTEST_SOURCE}
    BUILD ${GTEST_BUILD}
    RELEASE
    OPTIONS ${GTEST_CONFIG}
    DESTINATION ${GTEST_DEST}
    BUILD_COMMAND ${GTEST_BUILDCMD}
)

include_directories(${GTEST_HEADERS})
link_directories(${GTEST_LIBRARIES})
