set(THREADS_NUM 8)

if(NOT THREADS_NUM)
	set(THREADS_NUM 1)
endif()

set(OPENSSL_NAME openssl-3.0.9)
set(OPENSSL_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${OPENSSL_NAME})
set(OPENSSL_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${OPENSSL_NAME})
set(OPENSSL_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${OPENSSL_NAME}-build)
set(OPENSSL_HEADERS ${OPENSSL_DEST}/include/openssl)
set(OPENSSL_LIBRARIES ${OPENSSL_DEST}/lib64)
set(OPENSSL_CONFIG " \
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
")

set(OPENSSL_PATCHCMD " \
  ${CMAKE_COMMAND} -E make_directory ${OPENSSL_DEST}&&${CMAKE_COMMAND} -E make_directory ${OPENSSL_BUILD}&&${CMAKE_COMMAND} -E copy_directory ${OPENSSL_SOURCE} ${OPENSSL_BUILD}
")
  
set(OPENSSL_CONFIGURECMD " \
  ${CMAKE_COMMAND} -E chdir ${OPENSSL_BUILD} ./config  --prefix=${OPENSSL_DEST} 
")
set(OPENSSL_BUILDCMD " \
  ${CMAKE_COMMAND} -E chdir ${OPENSSL_BUILD} ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")
set(OPENSSL_INSTALLCMD " \
  ${CMAKE_COMMAND} -E chdir ${OPENSSL_BUILD} ${CMAKE_MAKE_PROGRAM} install -j${THREADS_NUM}
")
local_repo(
    ${OPENSSL_NAME}
    PATCH_COMMAND ${OPENSSL_PATCHCMD}
    CONFIGURE_COMMAND ${OPENSSL_CONFIGURECMD}
    INSTALL_COMMAND ${OPENSSL_INSTALLCMD}
    BUILD_COMMAND ${OPENSSL_BUILDCMD}
)

include_directories(BEFORE ${OPENSSL_HEADERS})
link_directories(BEFORE ${OPENSSL_LIBRARIES})


