if(NOT THREADS_NUM)
    set(THREADS_NUM 1)
endif()

set(PROTOBUF_NAME protobuf-3.21.12)
set(PROTOBUF_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${PROTOBUF_NAME})
set(PROTOBUF_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${PROTOBUF_NAME})
set(PROTOBUF_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${PROTOBUF_NAME}-build)
set(PROTOBUF_HEADERS ${PROTOBUF_DEST}/include)
set(PROTOBUF_LIBRARIES ${PROTOBUF_DEST}/lib)
set(PROTOBUF_CONFIG  " \
    -Dprotobuf_BUILD_CONFORMANCE=OFF \
    -Dprotobuf_BUILD_EXAMPLES=OFF \
    -Dprotobuf_BUILD_LIBPROTOC=ON \
    -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
    -Dprotobuf_BUILD_SHARED_LIBS=OFF \
    -Dprotobuf_BUILD_TESTS=OFF \
    -Dprotobuf_DISABLE_RTTI=ON \
    -Dprotobuf_INSTALL=ON \
    -Dprotobuf_INSTALL_EXAMPLES=OFF \
    -Dprotobuf_MSVC_STATIC_RUNTIME=OFF \
    -Dprotobuf_TEST_XML_OUTDIR=OFF \
    -Dprotobuf_USE_EXTERNAL_GTEST=OFF \
    -Dprotobuf_WITH_ZLIB=ON \
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
")
set(PROTOBUF_BUILDCMD " \
    ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")

local_repo_cmake(
    ${PROTOBUF_NAME}
    SOURCE ${PROTOBUF_SOURCE}
    BUILD ${PROTOBUF_BUILD}
    RELEASE
    OPTIONS ${PROTOBUF_CONFIG}
    DESTINATION ${PROTOBUF_DEST}
    BUILD_COMMAND ${PROTOBUF_BUILDCMD}
)

include_directories(${PROTOBUF_HEADERS})
link_directories(${PROTOBUF_LIBRARIES})
