set(THREADS_NUM 8)

if(NOT THREADS_NUM)
	set(THREADS_NUM 1)
endif()

set(SQLITE3_NAME sqlite3-3.11.0)
set(SQLITE3_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${SQLITE3_NAME})
set(SQLITE3_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${SQLITE3_NAME})
set(SQLITE3_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${SQLITE3_NAME}-build)
set(SQLITE3_HEADERS ${SQLITE3_DEST}/include)
set(SQLITE3_LIBRARIES ${SQLITE3_DEST}/lib)

set(SQLITE3_BUILDCMD " \
    ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")

set(SQLITE3_CONFIGURECMD " \
  ${CMAKE_COMMAND} -E chdir ${SQLITE3_BUILD} autoreconf -ivf && ${CMAKE_COMMAND} -E chdir ${SQLITE3_BUILD} ./configure  --prefix=${SQLITE3_DEST} 
")

local_repo_autotool(
    ${SQLITE3_NAME}
    SOURCE ${SQLITE3_SOURCE}
    BUILD ${SQLITE3_BUILD}
    SHARED
    DESTINATION ${SQLITE3_DEST}
    BUILD_COMMAND ${SQLITE3_BUILDCMD}
    CONFIGURE_COMMAND ${SQLITE3_CONFIGURECMD}
)

include_directories(BEFORE ${SQLITE3_HEADERS})
link_directories(BEFORE ${SQLITE3_LIBRARIES})
