if(NOT THREADS_NUM)
    set(THREADS_NUM)
endif()

set(WORKFLOW_NAME workflow-0.10.4)
set(WORKFLOW_SOURCE ${CMAKE_SOURCE_DIR}/vendors/${WORKFLOW_NAME})
set(WORKFLOW_DEST ${CMAKE_SOURCE_DIR}/thirdparty/${WORKFLOW_NAME})
set(WORKFLOW_BUILD ${CMAKE_SOURCE_DIR}/thirdparty/${WORKFLOW_NAME}-build)
set(WORKFLOW_HEADERS ${WORKFLOW_DEST}/include)
set(WORKFLOW_LIBRARIES ${WORKFLOW_DEST}/lib)
set(WORKFLOW_CONFIG " \
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
")
set(WORKFLOW_BUILDCMD " \
    ${CMAKE_MAKE_PROGRAM} -j${THREADS_NUM}
")

local_repo_cmake(
    ${WORKFLOW_NAME}
    SOURCE ${WORKFLOW_SOURCE}
    BUILD ${WORKFLOW_BUILD}
    RELEASE
    OPTIONS ${WORKFLOW_CONFIG}
    DESTINATION ${WORKFLOW_DEST}
    BUILD_COMMAND ${WORKFLOW_BUILDCMD}
)

include_directories(${WORKFLOW_HEADERS})
link_directories(${WORKFLOW_LIBRARIES})
